# Główny plik konfiguracji Semgrepa dla Custom-Steam-Dashboard
# Puste reguły na górnym poziomie - reguły będą ładowane z konkretnych plików
# poprzez flagi --config w linii poleceń

rules: []

# Uwaga: Aby uruchomić skan, używaj poleceń:
# semgrep scan --config=p/python --config=p/security-audit --config=semgrep/rules_backend_auth.yml server/
# lub
# semgrep scan --config=p/python --config=p/security-audit --config=semgrep/rules_frontend_client.yml app/



