#!/usr/bin/env python3
"""
Script to generate config.py with embedded values from environment variables.
This is run BEFORE PyInstaller build to hardcode values into the source.
"""

import os
import sys
from pathlib import Path

# Template for config.py with embedded values
CONFIG_TEMPLATE = '''"""
Configuration module for Custom Steam Dashboard client application.

AUTOGENERATED FILE - DO NOT EDIT MANUALLY!
This file was generated by generate_config.py during build process.

The values below are hardcoded from environment variables at build time.
"""

# ===== Server Configuration =====
# These values were embedded during build from environment variables
_SERVER_URL = "{server_url}"
_CLIENT_ID = "{client_id}"
_CLIENT_SECRET = "{client_secret}"


def get_server_url() -> str:
    """
    Get the server URL.
    
    Returns the hardcoded value that was embedded during build.
    
    Returns:
        Server URL string
    """
    return _SERVER_URL


def get_client_id() -> str:
    """
    Get the client ID.
    
    Returns the hardcoded value that was embedded during build.
    
    Returns:
        Client ID string
    """
    return _CLIENT_ID


def get_client_secret() -> str:
    """
    Get the client secret.
    
    Returns the hardcoded value that was embedded during build.
    
    Returns:
        Client secret string
    """
    return _CLIENT_SECRET
'''


def load_env_file(env_path: Path) -> dict:
    """Load variables from .env file."""
    env_vars = {}
    if env_path.exists():
        with open(env_path, 'r') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, value = line.split('=', 1)
                    # Remove quotes if present
                    value = value.strip('"').strip("'")
                    env_vars[key] = value
    return env_vars


def main():
    """Generate config.py with embedded values."""
    
    # Load from .env file if it exists
    env_file = Path('.env')
    if env_file.exists():
        print(f"Loading configuration from {env_file}...")
        env_vars = load_env_file(env_file)
        # Set in os.environ so getenv() works
        for key, value in env_vars.items():
            os.environ.setdefault(key, value)
    
    # Get values from environment (now including those from .env)
    server_url = os.getenv("SERVER_URL", "http://localhost:8000")
    client_id = os.getenv("CLIENT_ID", "desktop-main")
    client_secret = os.getenv("CLIENT_SECRET", "")
    
    # Validate
    if not client_secret:
        print("⚠️  WARNING: CLIENT_SECRET not set!")
        print("   Build will use empty secret (app won't authenticate)")
        response = input("Continue anyway? (y/N): ")
        if response.lower() != 'y':
            print("Aborting build.")
            sys.exit(1)
    
    # Show what will be embedded (hide secret)
    print("\nConfiguration to be embedded:")
    print(f"  SERVER_URL: {server_url}")
    print(f"  CLIENT_ID: {client_id}")
    print(f"  CLIENT_SECRET: {'*' * 10 if client_secret else '(empty)'}")
    print()
    
    # Generate config.py
    config_content = CONFIG_TEMPLATE.format(
        server_url=server_url,
        client_id=client_id,
        client_secret=client_secret
    )
    
    # Backup original config.py
    config_path = Path('app/config.py')
    backup_path = Path('app/config.py.backup')
    
    if config_path.exists():
        # Create backup
        with open(config_path, 'r') as f:
            original_content = f.read()
        with open(backup_path, 'w') as f:
            f.write(original_content)
        print(f"✓ Backed up original config.py to {backup_path}")
    
    # Write new config.py with embedded values
    with open(config_path, 'w') as f:
        f.write(config_content)
    
    print(f"✓ Generated {config_path} with embedded values")
    print(f"  (Original saved as {backup_path})")
    print()
    print("✓ Ready to build with PyInstaller!")
    print()
    
    return 0


if __name__ == "__main__":
    sys.exit(main())

